<a href="https://colab.research.google.com/github/girishpatil935/Gradient-Data-Analytics-Hackathon/blob/main/Hackthon_datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [ ]:
file_path = "/content/Dataset.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Sheets available:")
for sheet in excel_file.sheet_names:
    print("-", sheet)

Sheets available:
- orders
- order_items
- order_payments
- order_reviews
- customers
- products
- sellers
- geolocation
- category_translation

In [ ]:
tables = {}

for sheet in excel_file.sheet_names:
    tables[sheet] = pd.read_excel(file_path, sheet_name=sheet)

print("Datasets loaded successfully!\n")

for name, df in tables.items():
    print(name, "→", df.shape)

Datasets loaded successfully!

orders → (99441, 8)
order_items → (112650, 6)
order_payments → (103886, 5)
order_reviews → (100000, 7)
customers → (99441, 5)
products → (32951, 9)
sellers → (3095, 4)
geolocation → (1000163, 5)
category_translation → (71, 2)

In [ ]:
orders = tables["orders"]

print("Number of rows:", len(orders))

Number of rows: 99441

In [ ]:
print("Number of columns:", len(orders.columns))

Number of columns: 8

In [ ]:
print("Column names:")
for i, column in enumerate(orders.columns, start=1):
    print(i, "→", column)

Column names:
1 → order_id
2 → customer_id
3 → order_status
4 → order_purchase_timestamp
5 → order_approved_at
6 → order_delivered_carrier_date
7 → order_delivered_customer_date
8 → order_estimated_delivery_date

In [ ]:
print(orders.dtypes)

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [ ]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
orders.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [ ]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

print("=" * 70)
print("ORDER TIMESTAMPS CONVERTED")
print("=" * 70)

print(orders[date_columns].dtypes)

======================================================================
ORDER TIMESTAMPS CONVERTED
======================================================================
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [ ]:
# ============================================================
# CELL 1 — IMPORTS + LOCATE DATASET
# ============================================================

import pandas as pd
import numpy as np
import os

print("=" * 70)
print("PHASE 1 — INITIALIZATION")
print("=" * 70)

# Try the common Colab locations.
possible_paths = [
    "/content/Dataset.xlsx",
    "Dataset.xlsx",
    "/mnt/data/Dataset.xlsx"
]

DATASET_PATH = None

for path in possible_paths:
    if os.path.exists(path):
        DATASET_PATH = path
        break

if DATASET_PATH is None:
    raise FileNotFoundError(
        "Dataset.xlsx was not found in the current Colab runtime. "
        "If you already uploaded it to Colab, check the Files panel."
    )

print("Dataset found at:")
print(DATASET_PATH)

# Open workbook
xls = pd.ExcelFile(DATASET_PATH)

print("\nSheets available:")
for sheet in xls.sheet_names:
    print("-", sheet)

======================================================================
PHASE 1 — INITIALIZATION
======================================================================
Dataset found at:
/content/Dataset.xlsx

Sheets available:
- orders
- order_items
- order_payments
- order_reviews
- customers
- products
- sellers
- geolocation
- category_translation

In [ ]:
# ============================================================
# CELL 2 — LOAD ALL REQUIRED SHEETS
# ============================================================

print("=" * 70)
print("LOADING DATASETS")
print("=" * 70)

orders = pd.read_excel(
    DATASET_PATH,
    sheet_name="orders"
)

order_items = pd.read_excel(
    DATASET_PATH,
    sheet_name="order_items"
)

order_payments = pd.read_excel(
    DATASET_PATH,
    sheet_name="order_payments"
)

order_reviews = pd.read_excel(
    DATASET_PATH,
    sheet_name="order_reviews"
)

customers = pd.read_excel(
    DATASET_PATH,
    sheet_name="customers"
)

products = pd.read_excel(
    DATASET_PATH,
    sheet_name="products"
)

category_translation = pd.read_excel(
    DATASET_PATH,
    sheet_name="category_translation"
)

print("Orders:", orders.shape)
print("Order items:", order_items.shape)
print("Payments:", order_payments.shape)
print("Reviews:", order_reviews.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Category translation:", category_translation.shape)

======================================================================
LOADING DATASETS
======================================================================
Orders: (99441, 8)
Order items: (112650, 6)
Payments: (103886, 5)
Reviews: (100000, 7)
Customers: (99441, 5)
Products: (32951, 9)
Category translation: (71, 2)

In [ ]:
# ============================================================
# CELL 3 — COLUMN VALIDATION
# ============================================================

datasets = {
    "orders": orders,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "customers": customers,
    "products": products,
    "category_translation": category_translation
}

for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)

    print("Rows:", len(df))
    print("Columns:")

    for i, col in enumerate(df.columns, start=1):
        print(f"{i}. {col}")

======================================================================
ORDERS
======================================================================
Rows: 99441
Columns:
1. order_id
2. customer_id
3. order_status
4. order_purchase_timestamp
5. order_approved_at
6. order_delivered_carrier_date
7. order_delivered_customer_date
8. order_estimated_delivery_date

======================================================================
ORDER_ITEMS
======================================================================
Rows: 112650
Columns:
1. order_id
2. order_item_id
3. product_id
4. seller_id
5. price
6. freight_value

======================================================================
ORDER_PAYMENTS
======================================================================
Rows: 103886
Columns:
1. order_id
2. payment_sequential
3. payment_type
4. payment_installments
5. payment_value

======================================================================
ORDER_REVIEWS
======================================================================
Rows: 100000
Columns:
1. review_id
2. order_id
3. review_score
4. review_comment_title
5. review_comment_message
6. review_creation_date
7. review_answer_timestamp

======================================================================
CUSTOMERS
======================================================================
Rows: 99441
Columns:
1. customer_id
2. customer_unique_id
3. customer_zip_code_prefix
4. customer_city
5. customer_state

======================================================================
PRODUCTS
======================================================================
Rows: 32951
Columns:
1. product_id
2. product_category_name
3. product_name_lenght
4. product_description_lenght
5. product_photos_qty
6. product_weight_g
7. product_length_cm
8. product_height_cm
9. product_width_cm

======================================================================
CATEGORY_TRANSLATION
======================================================================
Rows: 71
Columns:
1. product_category_name
2. product_category_name_english

In [ ]:
# ============================================================
# CELL 4 — CLEAN ORDER TIMESTAMPS
# ============================================================

print("=" * 70)
print("CLEANING ORDER TIMESTAMPS")
print("=" * 70)

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(
        orders[col],
        errors="coerce"
    )

print("Datetime conversion complete.")

print("\nMissing datetime values:")
print(orders[date_columns].isnull().sum())

======================================================================
CLEANING ORDER TIMESTAMPS
======================================================================
Datetime conversion complete.

Missing datetime values:
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
# ============================================================
# CELL 5 — ORDER TABLE VALIDATION
# ============================================================

print("=" * 70)
print("ORDERS VALIDATION")
print("=" * 70)

print("Rows:", len(orders))
print("Unique order IDs:", orders["order_id"].nunique())
print("Duplicate order IDs:", orders["order_id"].duplicated().sum())

assert orders["order_id"].nunique() == len(orders), \
    "Orders table contains duplicate order IDs."

print("\nOrder status distribution:")
print(orders["order_status"].value_counts(dropna=False))

print("\nCustomer ID missing:")
print(orders["customer_id"].isnull().sum())

======================================================================
ORDERS VALIDATION
======================================================================
Rows: 99441
Unique order IDs: 99441
Duplicate order IDs: 0

Order status distribution:
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

Customer ID missing:
0

In [ ]:
# ============================================================
# CELL 6 — ORDER-LEVEL ITEM SUMMARY
# ============================================================

print("=" * 70)
print("CREATING ORDER-LEVEL ITEM SUMMARY")
print("=" * 70)

# Make sure numeric columns are numeric
order_items["order_item_id"] = pd.to_numeric(
    order_items["order_item_id"],
    errors="coerce"
)

order_items["price"] = pd.to_numeric(
    order_items["price"],
    errors="coerce"
)

order_items["freight_value"] = pd.to_numeric(
    order_items["freight_value"],
    errors="coerce"
)

item_summary = (
    order_items
    .groupby("order_id")
    .agg(
        item_count=("order_item_id", "count"),
        unique_products=("product_id", "nunique"),
        unique_sellers=("seller_id", "nunique"),
        product_value=("price", "sum"),
        freight_value=("freight_value", "sum")
    )
    .reset_index()
)

item_summary["order_value"] = (
    item_summary["product_value"] +
    item_summary["freight_value"]
)

print("Orders represented:", len(item_summary))
print("Unique order IDs:", item_summary["order_id"].nunique())
print("Duplicate order IDs:", item_summary["order_id"].duplicated().sum())

display(item_summary.head())

======================================================================
CREATING ORDER-LEVEL ITEM SUMMARY
======================================================================
Orders represented: 98666
Unique order IDs: 98666
Duplicate order IDs: 0

,order_id,item_count,unique_products,unique_sellers,product_value,freight_value,order_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,1,1,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,199.90,18.14,218.04

In [ ]:

print("=" * 70)
print("CREATING PAYMENT SUMMARY")
print("=" * 70)

order_payments["payment_value"] = pd.to_numeric(
    order_payments["payment_value"],
    errors="coerce"
)

order_payments["payment_installments"] = pd.to_numeric(
    order_payments["payment_installments"],
    errors="coerce"
)

payment_summary = (
    order_payments
    .groupby("order_id")
    .agg(
        total_payment_value=("payment_value", "sum"),
        payment_count=("payment_sequential", "count"),
        max_installments=("payment_installments", "max")
    )
    .reset_index()
)

print("Orders represented:", len(payment_summary))
print("Unique order IDs:", payment_summary["order_id"].nunique())
print("Duplicate order IDs:", payment_summary["order_id"].duplicated().sum())

# Special payment validation
max_payment_order = (
    payment_summary
    .sort_values("payment_count", ascending=False)
    .head(1)
)

print("\nHighest payment-count order:")
display(max_payment_order)

======================================================================
CREATING PAYMENT SUMMARY
======================================================================
Orders represented: 99440
Unique order IDs: 99440
Duplicate order IDs: 0

Highest payment-count order:

                               order_id  total_payment_value  payment_count  max_installments
97261  fa65dad1b0e818e3ccc5cb0e39231352               457.99             29                 1

In [ ]:
print("=" * 70)
print("CREATING REVIEW SUMMARY")
print("=" * 70)

order_reviews["review_score"] = pd.to_numeric(
    order_reviews["review_score"],
    errors="coerce"
)

review_summary = (
    order_reviews
    .groupby("order_id")
    .agg(
        review_count=("review_id", "count"),
        review_score_mean=("review_score", "mean"),
        review_score_min=("review_score", "min"),
        review_score_max=("review_score", "max")
    )
    .reset_index()
)

print("Orders represented:", len(review_summary))
print("Unique order IDs:", review_summary["order_id"].nunique())
print("Duplicate order IDs:", review_summary["order_id"].duplicated().sum())

# Detect conflicting review scores
review_conflicts = (
    order_reviews
    .groupby("order_id")["review_score"]
    .nunique()
)

conflicting_orders = review_conflicts[
    review_conflicts > 1
]

print("\nOrders with conflicting review scores:",
      len(conflicting_orders))

print("\nFirst 20 conflicting orders:")
display(conflicting_orders.head(20))

======================================================================
CREATING REVIEW SUMMARY
======================================================================
Orders represented: 99441
Unique order IDs: 99441
Duplicate order IDs: 0

Orders with conflicting review scores: 209

First 20 conflicting orders:

order_id
013056cfe49763c6f66bda03396c5ee3    2
02355020fd0a40a0d56df9f6ff060413    2
029863af4b968de1e5d6a82782e662f5    2
03c939fd7fd3b38f8485a0f95798f1f6    2
03eba6d9fef8f5b3e811d4b5a7cca9cd    2
04f1827088d972a62224f5203a071500    2
0544030711e50ec2cb6c15764d22891a    2
059bbeb3477ed66fd7e670c3f879009a    2
073fa4be4665f397a289842b1053229c    2
075a544c5f4ed4bb75f82b160465fe76    2
08bf75dcf867b9f13026785053e87052    2
095e9e0811476409362d72fa70d73a6c    2
09a38776c4e31230864f867821174daa    2
14d35062b86c2e1f69376af68e9e2a1e    2
14f75c9606fc12baa607bebe380d7237    2
151e44f3dd461fe0838b6f59f884749f    2
1549221b1b6e8fec6d2f9890932333f1    2
15fc22aad8d1b227891ce61eff4128cd    2
171c9f9a5667b0bea55d8b78c27bc5bd    2
17df2cc060680fc1712991499b645cd2    2
Name: review_score, dtype: int64

In [ ]:
print("=" * 70)
print("BUILDING MASTER V1")
print("=" * 70)

# Start from orders because MASTER V1 is one row per order.
master_v1 = orders.copy()

# Merge item summary
master_v1 = master_v1.merge(
    item_summary,
    on="order_id",
    how="left",
    validate="one_to_one"
)

# Merge payment summary
master_v1 = master_v1.merge(
    payment_summary,
    on="order_id",
    how="left",
    validate="one_to_one"
)

# Merge review summary
master_v1 = master_v1.merge(
    review_summary,
    on="order_id",
    how="left",
    validate="one_to_one"
)

print("Rows:", len(master_v1))
print("Unique order IDs:", master_v1["order_id"].nunique())
print("Duplicate order IDs:",
      master_v1["order_id"].duplicated().sum())

======================================================================
BUILDING MASTER V1
======================================================================
Rows: 99441
Unique order IDs: 99441
Duplicate order IDs: 0

In [ ]:
print("=" * 70)
print("CREATING DELIVERY FEATURES")
print("=" * 70)

master_v1["delivery_days"] = (
    master_v1["order_delivered_customer_date"]
    - master_v1["order_purchase_timestamp"]
).dt.total_seconds() / 86400

master_v1["estimated_delivery_days"] = (
    master_v1["order_estimated_delivery_date"]
    - master_v1["order_purchase_timestamp"]
).dt.total_seconds() / 86400

master_v1["delivery_delay_days"] = (
    master_v1["order_delivered_customer_date"]
    - master_v1["order_estimated_delivery_date"]
).dt.total_seconds() / 86400

# Use pandas nullable integer type for the label
master_v1["delivery_performance"] = pd.Series(
    pd.NA,
    index=master_v1.index,
    dtype="string"
)

delivered_mask = (
    master_v1["order_delivered_customer_date"].notna()
)

master_v1.loc[
    delivered_mask &
    (master_v1["delivery_delay_days"] <= 0),
    "delivery_performance"
] = "On Time"

master_v1.loc[
    delivered_mask &
    (master_v1["delivery_delay_days"] > 0),
    "delivery_performance"
] = "Late"

print("Delivery performance:")
print(
    master_v1["delivery_performance"]
    .value_counts(dropna=False)
)

======================================================================
CREATING DELIVERY FEATURES
======================================================================
Delivery performance:
delivery_performance
On Time    88649
Late        7827
<NA>        2965
Name: count, dtype: Int64

In [ ]:
print("=" * 70)
print("MASTER V1 VALIDATION")
print("=" * 70)

print("Rows:", len(master_v1))
print("Columns:", len(master_v1.columns))
print("Unique order IDs:", master_v1["order_id"].nunique())
print("Duplicate order IDs:",
      master_v1["order_id"].duplicated().sum())

assert len(master_v1) == 99441, \
    f"Expected 99,441 rows, got {len(master_v1)}"

assert master_v1["order_id"].nunique() == 99441, \
    "MASTER V1 does not contain 99,441 unique orders."

assert master_v1["order_id"].duplicated().sum() == 0, \
    "MASTER V1 contains duplicate order IDs."

print("\nMASTER V1 structure is valid.")

print("\nMissing values:")
print(
    master_v1.isnull()
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

======================================================================
MASTER V1 VALIDATION
======================================================================
Rows: 99441
Columns: 25
Unique order IDs: 99441
Duplicate order IDs: 0

MASTER V1 structure is valid.

Missing values:
order_delivered_customer_date    2965
delivery_days                    2965
delivery_delay_days              2965
delivery_performance             2965
order_delivered_carrier_date     1783
unique_products                   775
item_count                        775
unique_sellers                    775
order_value                       775
product_value                     775
freight_value                     775
order_approved_at                 160
max_installments                    1
total_payment_value                 1
payment_count                       1
order_id                            0
order_purchase_timestamp            0
order_estimated_delivery_date       0
customer_id                         0
order_status                        0
dtype: int64

In [ ]:
print("=" * 70)
print("PREPARING PRODUCT DATA")
print("=" * 70)

# Keep only useful product columns
product_cols = [
    "product_id",
    "product_category_name",
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

product_cols = [
    col for col in product_cols
    if col in products.columns
]

products_clean = products[product_cols].copy()

# Create product volume
if all(
    col in products_clean.columns
    for col in [
        "product_length_cm",
        "product_height_cm",
        "product_width_cm"
    ]
):

    products_clean["product_volume_cm3"] = (
        products_clean["product_length_cm"]
        * products_clean["product_height_cm"]
        * products_clean["product_width_cm"]
    )

# Clean translation table
category_translation = category_translation.copy()

print("Products:", len(products_clean))
print("Category translations:", len(category_translation))

print("\nProduct columns:")
print(products_clean.columns.tolist())

print("\nTranslation columns:")
print(category_translation.columns.tolist())

======================================================================
PREPARING PRODUCT DATA
======================================================================
Products: 32951
Category translations: 71

Product columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'product_volume_cm3']

Translation columns:
['product_category_name', 'product_category_name_english']

In [ ]:
print("=" * 70)
print("CREATING ITEM + PRODUCT DATASET")
print("=" * 70)

item_product = order_items.merge(
    products_clean,
    on="product_id",
    how="left"
)

print("Rows:", len(item_product))

print(
    "Missing product matches:",
    item_product["product_category_name"].isna().sum()
)

display(item_product.head())

======================================================================
CREATING ITEM + PRODUCT DATASET
======================================================================
Rows: 112650
Missing product matches: 1603

,order_id,order_item_id,product_id,seller_id,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0,3528.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0,60000.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0,14157.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0,2400.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0,42000.0

In [ ]:
print("=" * 70)
print("ADDING ENGLISH CATEGORIES")
print("=" * 70)

# Standard Olist translation columns:
# product_category_name -> product_category_name_english

translation_cols = category_translation.columns.tolist()

print("Translation columns:", translation_cols)

# Rename only if standard columns exist
if (
    "product_category_name" in category_translation.columns
    and
    "product_category_name_english" in category_translation.columns
):

    category_translation_clean = (
        category_translation[
            [
                "product_category_name",
                "product_category_name_english"
            ]
        ]
        .drop_duplicates("product_category_name")
    )

    item_product = item_product.merge(
        category_translation_clean,
        on="product_category_name",
        how="left"
    )

else:
    raise ValueError(
        "Expected category translation columns were not found."
    )

print(
    "Missing English categories:",
    item_product["product_category_name_english"].isna().sum()
)

display(
    item_product[
        [
            "product_id",
            "product_category_name",
            "product_category_name_english"
        ]
    ].head(10)
)

======================================================================
ADDING ENGLISH CATEGORIES
======================================================================
Translation columns: ['product_category_name', 'product_category_name_english']
Missing English categories: 1627

                         product_id  product_category_name product_category_name_english
0  4244733e06e7ecb4970a6e2683c13e61             cool_stuff                    cool_stuff
1  e5f2d52b802189ee658865ca93d83a8f               pet_shop                      pet_shop
2  c777355d18b72b67abbeef9df44fd0fd       moveis_decoracao               furniture_decor
3  7634da152a4610f1595efa32f14722fc             perfumaria                     perfumery
4  ac6c3623068f30de03045865e4e10089     ferramentas_jardim                  garden_tools
5  ef92defde845ab8450f9d70c526ef70f  utilidades_domesticas                    housewares
6  8d4f2bb7e93e6710a28f34fa83ee7d28              telefonia                     telephony
7  557d850972a7d6f792fd18ae1400d9b6     ferramentas_jardim                  garden_tools
8  310ae3c140ff94b03219ad0adc3c778f           beleza_saude                 health_beauty
9  4535b0e1091c278dfd193e5a1d63b39f        livros_tecnicos               books_technical

In [ ]:
print("=" * 70)
print("ORDER-LEVEL PRODUCT & CATEGORY AGGREGATION")
print("=" * 70)

# Helper function to safely join unique categories
def join_unique_categories(series):
    values = (
        series
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    values = sorted(values)

    if len(values) == 0:
        return pd.NA

    return "|".join(values)


product_order_summary = (
    item_product
    .groupby("order_id")
    .agg(
        product_category_count=(
            "product_category_name_english",
            "nunique"
        ),

        primary_category=(
            "product_category_name_english",
            lambda x: (
                x.mode().iloc[0]
                if not x.mode().empty
                else pd.NA
            )
        ),

        product_categories=(
            "product_category_name_english",
            join_unique_categories
        ),

        avg_product_price=(
            "price",
            "mean"
        ),

        min_product_price=(
            "price",
            "min"
        ),

        max_product_price=(
            "price",
            "max"
        ),

        total_product_photos=(
            "product_photos_qty",
            "sum"
        ),

        avg_product_photos_qty=(
            "product_photos_qty",
            "mean"
        ),

        avg_product_weight_g=(
            "product_weight_g",
            "mean"
        ),

        avg_product_volume_cm3=(
            "product_volume_cm3",
            "mean"
        )
    )
    .reset_index()
)

product_order_summary["has_multiple_categories"] = (
    product_order_summary["product_category_count"] > 1
)

print("Orders represented:",
      len(product_order_summary))

print("Unique order IDs:",
      product_order_summary["order_id"].nunique())

print("Duplicate order IDs:",
      product_order_summary["order_id"].duplicated().sum())

print(
    "\nOrders with multiple categories:",
    product_order_summary["has_multiple_categories"]
    .sum()
)

display(product_order_summary.head())

======================================================================
ORDER-LEVEL PRODUCT & CATEGORY AGGREGATION
======================================================================
Orders represented: 98666
Unique order IDs: 98666
Duplicate order IDs: 0

Orders with multiple categories: 726

,order_id,product_category_count,primary_category,product_categories,avg_product_price,min_product_price,max_product_price,total_product_photos,avg_product_photos_qty,avg_product_weight_g,avg_product_volume_cm3,has_multiple_categories
0,00010242fe8c5a6d1ba2dd792cb16214,1,cool_stuff,cool_stuff,58.90,58.90,58.90,4.0,4.0,650.0,3528.0,False
1,00018f77f2f0320c557190d7a144bdd3,1,pet_shop,pet_shop,239.90,239.90,239.90,2.0,2.0,30000.0,60000.0,False
2,000229ec398224ef6ca0657da4fc703e,1,furniture_decor,furniture_decor,199.00,199.00,199.00,2.0,2.0,3050.0,14157.0,False
3,00024acbcdf0a6daa1e931b038114c75,1,perfumery,perfumery,12.99,12.99,12.99,1.0,1.0,200.0,2400.0,False
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,garden_tools,garden_tools,199.90,199.90,199.90,1.0,1.0,3750.0,42000.0,False

In [ ]:
print("=" * 70)
print("ADDING PRODUCT FEATURES TO MASTER V1")
print("=" * 70)

master_v1 = master_v1.merge(
    product_order_summary,
    on="order_id",
    how="left",
    validate="one_to_one"
)

print("Rows:", len(master_v1))
print("Unique orders:", master_v1["order_id"].nunique())
print("Duplicate orders:",
      master_v1["order_id"].duplicated().sum())

assert len(master_v1) == 99441
assert master_v1["order_id"].nunique() == 99441
assert master_v1["order_id"].duplicated().sum() == 0

print("\nProduct enrichment successful.")

======================================================================
ADDING PRODUCT FEATURES TO MASTER V1
======================================================================
Rows: 99441
Unique orders: 99441
Duplicate orders: 0

Product enrichment successful.

In [ ]:
print("=" * 70)
print("SPEND-WEIGHTED CATEGORY FEATURES")
print("=" * 70)

# Create item-level category spending dataset
item_category_spend = item_product[
    [
        "order_id",
        "product_category_name_english",
        "price"
    ]
].copy()

item_category_spend["price"] = pd.to_numeric(
    item_category_spend["price"],
    errors="coerce"
)

print("Rows:", len(item_category_spend))

print(
    "Missing category:",
    item_category_spend[
        "product_category_name_english"
    ].isna().sum()
)

# Remove rows where category cannot be identified
category_spend_valid = (
    item_category_spend
    .dropna(subset=["product_category_name_english"])
)

# Aggregate by order + category
order_category_spend = (
    category_spend_valid
    .groupby(
        [
            "order_id",
            "product_category_name_english"
        ]
    )
    .agg(
        category_spend=("price", "sum")
    )
    .reset_index()
)

print(
    "\nOrder-category rows:",
    len(order_category_spend)
)

======================================================================
SPEND-WEIGHTED CATEGORY FEATURES
======================================================================
Rows: 112650
Missing category: 1627

Order-category rows: 97997

In [ ]:
print("=" * 70)
print("CALCULATING SPEND CONCENTRATION")
print("=" * 70)

# Total identified category spend
order_category_totals = (
    order_category_spend
    .groupby("order_id")
    ["category_spend"]
    .sum()
    .rename("category_identified_spend")
)

# Number of identified categories
order_category_counts = (
    order_category_spend
    .groupby("order_id")
    ["product_category_name_english"]
    .nunique()
    .rename("category_spend_count")
)

# Highest-spend category
top_category = (
    order_category_spend
    .sort_values(
        [
            "order_id",
            "category_spend"
        ],
        ascending=[True, False]
    )
    .drop_duplicates("order_id")
)

top_category = top_category[
    [
        "order_id",
        "product_category_name_english",
        "category_spend"
    ]
].rename(
    columns={
        "product_category_name_english":
            "top_spend_category",
        "category_spend":
            "top_category_spend"
    }
)

# Combine
spend_features = (
    order_category_totals
    .to_frame()
    .join(order_category_counts)
    .reset_index()
    .merge(
        top_category,
        on="order_id",
        how="left",
        validate="one_to_one"
    )
)

# Top category share
spend_features["top_category_spend_share"] = (
    spend_features["top_category_spend"]
    /
    spend_features["category_identified_spend"]
)

# Herfindahl-style category concentration:
# sum of squared category spending shares
order_category_spend["spend_share"] = (
    order_category_spend["category_spend"]
    /
    order_category_spend
    .groupby("order_id")["category_spend"]
    .transform("sum")
)

concentration = (
    order_category_spend
    .assign(
        squared_share=lambda x:
        x["spend_share"] ** 2
    )
    .groupby("order_id")["squared_share"]
    .sum()
    .rename("category_spend_concentration")
)

spend_features = spend_features.merge(
    concentration,
    on="order_id",
    how="left",
    validate="one_to_one"
)

print("Orders represented:",
      len(spend_features))

print("Duplicate order IDs:",
      spend_features["order_id"].duplicated().sum())

display(spend_features.head(10))

======================================================================
CALCULATING SPEND CONCENTRATION
======================================================================
Orders represented: 97256
Duplicate order IDs: 0

,order_id,category_identified_spend,category_spend_count,top_spend_category,top_category_spend,top_category_spend_share,category_spend_concentration
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,1,cool_stuff,58.90,1.0,1.0
1,00018f77f2f0320c557190d7a144bdd3,239.90,1,pet_shop,239.90,1.0,1.0
2,000229ec398224ef6ca0657da4fc703e,199.00,1,furniture_decor,199.00,1.0,1.0
3,00024acbcdf0a6daa1e931b038114c75,12.99,1,perfumery,12.99,1.0,1.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,1,garden_tools,199.90,1.0,1.0
5,00048cc3ae777c65dbb7d2a0634bc1ea,21.90,1,housewares,21.90,1.0,1.0
6,00054e8431b9d7675808bcb819fb4a32,19.90,1,telephony,19.90,1.0,1.0
7,000576fe39319847cbb9d288c5617fa6,810.00,1,garden_tools,810.00,1.0,1.0
8,0005a1a1728c9d785b8e2b08b904576c,145.95,1,health_beauty,145.95,1.0,1.0
9,0005f50442cb953dcd1d21e1fb923495,53.99,1,books_technical,53.99,1.0,1.0

In [ ]:
print("=" * 70)
print("ADDING SPEND FEATURES")
print("=" * 70)

master_v1 = master_v1.merge(
    spend_features,
    on="order_id",
    how="left",
    validate="one_to_one"
)

print("Rows:", len(master_v1))
print("Unique orders:", master_v1["order_id"].nunique())
print("Duplicate orders:",
      master_v1["order_id"].duplicated().sum())

assert len(master_v1) == 99441
assert master_v1["order_id"].nunique() == 99441
assert master_v1["order_id"].duplicated().sum() == 0

print("\nSpend enrichment successful.")

======================================================================
ADDING SPEND FEATURES
======================================================================
Rows: 99441
Unique orders: 99441
Duplicate orders: 0

Spend enrichment successful.

In [ ]:
print("=" * 70)
print("PREPARING CUSTOMER INFORMATION")
print("=" * 70)

customer_columns = [
    "customer_id",
    "customer_unique_id"
]

customer_clean = customers[
    [
        col for col in customer_columns
        if col in customers.columns
    ]
].copy()

# Ensure customer_id is unique before merging
customer_clean = (
    customer_clean
    .drop_duplicates("customer_id")
)

master_v1 = master_v1.merge(
    customer_clean,
    on="customer_id",
    how="left",
    validate="one_to_one"
)

print("Rows:", len(master_v1))
print("Unique orders:", master_v1["order_id"].nunique())
print("Duplicate orders:",
      master_v1["order_id"].duplicated().sum())

print(
    "\nMissing customer_unique_id:",
    master_v1["customer_unique_id"].isna().sum()
)

assert len(master_v1) == 99441
assert master_v1["order_id"].duplicated().sum() == 0

======================================================================
PREPARING CUSTOMER INFORMATION
======================================================================
Rows: 99441
Unique orders: 99441
Duplicate orders: 0

Missing customer_unique_id: 0

In [ ]:
print("=" * 70)
print("CREATING CUSTOMER-LEVEL FEATURES")
print("=" * 70)

# Only customers with a valid customer_unique_id
customer_valid = master_v1[
    master_v1["customer_unique_id"].notna()
].copy()

print(
    "Orders with valid customer_unique_id:",
    len(customer_valid)
)

print(
    "Orders without customer_unique_id:",
    len(master_v1) - len(customer_valid)
)

# ------------------------------------------------------------
# Basic customer behavior
# ------------------------------------------------------------

customer_features = (
    customer_valid
    .groupby("customer_unique_id")
    .agg(
        customer_order_count=(
            "order_id",
            "nunique"
        ),

        customer_total_spend=(
            "order_value",
            "sum"
        ),

        customer_avg_order_value=(
            "order_value",
            "mean"
        ),

        customer_avg_review_score=(
            "review_score_mean",
            "mean"
        ),

        customer_late_order_rate=(
            "delivery_performance",
            lambda x: (
                (x == "Late").sum()
                /
                x.notna().sum()
                if x.notna().sum() > 0
                else np.nan
            )
        ),

        customer_avg_delivery_delay=(
            "delivery_delay_days",
            "mean"
        ),

        customer_category_diversity=(
            "primary_category",
            "nunique"
        )
    )
    .reset_index()
)

# Repeat purchase indicator
customer_features[
    "customer_repeat_purchase_indicator"
] = (
    customer_features["customer_order_count"] > 1
).astype("int64")

print("Customer records created:",
      len(customer_features))

display(customer_features.head(10))

======================================================================
CREATING CUSTOMER-LEVEL FEATURES
======================================================================
Orders with valid customer_unique_id: 99441
Orders without customer_unique_id: 0
Customer records created: 96096

,customer_unique_id,customer_order_count,customer_total_spend,customer_avg_order_value,customer_avg_review_score,customer_late_order_rate,customer_avg_delivery_delay,customer_category_diversity,customer_repeat_purchase_indicator
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,141.90,5.0,0.0,-4.132905,1,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,27.19,4.0,0.0,-4.248125,1,0
2,0000f46a3911fa3c0805444483337064,1,86.22,86.22,3.0,0.0,-1.389734,1,0
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,43.62,4.0,0.0,-11.108970,1,0
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,196.89,5.0,0.0,-7.035463,1,0
5,0004bd2a26a76fe21f786e4fbd80607f,1,166.98,166.98,4.0,0.0,-11.324502,1,0
6,00050ab1314c0e55a6ca13cf7181fecf,1,35.38,35.38,4.0,0.0,-11.493762,1,0
7,00053a61a98854899e70ed204dd4bafe,1,419.18,419.18,1.0,0.0,-9.206354,1,0
8,0005e1862207bf6ccc02e4228effd9a0,1,150.12,150.12,4.0,0.0,-27.643657,1,0
9,0005ef4cd20d2893f0d9fbd94d3c0d97,1,129.76,129.76,1.0,1.0,31.526829,1,0

In [ ]:
print("=" * 70)
print("MERGING CUSTOMER FEATURES")
print("=" * 70)

master_v1 = master_v1.merge(
    customer_features,
    on="customer_unique_id",
    how="left",
    validate="many_to_one"
)

print("Rows:", len(master_v1))
print("Unique order IDs:",
      master_v1["order_id"].nunique())

print("Duplicate order IDs:",
      master_v1["order_id"].duplicated().sum())

assert len(master_v1) == 99441
assert master_v1["order_id"].nunique() == 99441
assert master_v1["order_id"].duplicated().sum() == 0

print("\nCustomer enrichment successful.")

======================================================================
MERGING CUSTOMER FEATURES
======================================================================
Rows: 99441
Unique order IDs: 99441
Duplicate order IDs: 0

Customer enrichment successful.

In [ ]:
print("=" * 70)
print("CUSTOMER ID SAFETY VALIDATION")
print("=" * 70)

missing_customer_mask = (
    master_v1["customer_unique_id"].isna()
)

customer_feature_columns = [
    "customer_order_count",
    "customer_total_spend",
    "customer_avg_order_value",
    "customer_avg_review_score",
    "customer_late_order_rate",
    "customer_avg_delivery_delay",
    "customer_category_diversity",
    "customer_repeat_purchase_indicator"
]

print(
    "Orders with missing customer_unique_id:",
    missing_customer_mask.sum()
)

print("\nCustomer features for missing customer IDs:")

display(
    master_v1.loc[
        missing_customer_mask,
        customer_feature_columns
    ].head(20)
)

# Customer-level features MUST remain missing
# when customer identity is unavailable.

for col in customer_feature_columns:

    non_missing_features = (
        master_v1.loc[
            missing_customer_mask,
            col
        ]
        .notna()
        .sum()
    )

    print(
        f"{col}:",
        non_missing_features,
        "non-missing values"
    )

    assert non_missing_features == 0, (
        f"{col} contains a misleading customer-level "
        "value for a missing customer_unique_id."
    )

print(
    "\nPASS — Missing customer IDs were not assigned "
    "fake customer-level statistics."
)

======================================================================
CUSTOMER ID SAFETY VALIDATION
======================================================================
Orders with missing customer_unique_id: 0

Customer features for missing customer IDs:

Empty DataFrame
Columns: [customer_order_count, customer_total_spend, customer_avg_order_value, customer_avg_review_score, customer_late_order_rate, customer_avg_delivery_delay, customer_category_diversity, customer_repeat_purchase_indicator]
Index: []

customer_order_count: 0 non-missing values
customer_total_spend: 0 non-missing values
customer_avg_order_value: 0 non-missing values
customer_avg_review_score: 0 non-missing values
customer_late_order_rate: 0 non-missing values
customer_avg_delivery_delay: 0 non-missing values
customer_category_diversity: 0 non-missing values
customer_repeat_purchase_indicator: 0 non-missing values

PASS — Missing customer IDs were not assigned fake customer-level statistics.

In [ ]:
print("=" * 70)
print("CUSTOMER FEATURE VALIDATION")
print("=" * 70)

print("Rows:", len(master_v1))
print("Unique order IDs:",
      master_v1["order_id"].nunique())

print(
    "Duplicate order IDs:",
    master_v1["order_id"].duplicated().sum()
)

print("\nCustomer feature missing values:")

customer_missing = (
    master_v1[
        customer_feature_columns
    ]
    .isna()
    .sum()
)

print(customer_missing)

print("\nCustomer feature distributions:")

display(
    master_v1[
        customer_feature_columns
    ].describe()
)

======================================================================
CUSTOMER FEATURE VALIDATION
======================================================================
Rows: 99441
Unique order IDs: 99441
Duplicate order IDs: 0

Customer feature missing values:
customer_order_count                     0
customer_total_spend                     0
customer_avg_order_value               685
customer_avg_review_score                0
customer_late_order_rate              2760
customer_avg_delivery_delay           2760
customer_category_diversity              0
customer_repeat_purchase_indicator       0
dtype: int64

Customer feature distributions:

,customer_order_count,customer_total_spend,customer_avg_order_value,customer_avg_review_score,customer_late_order_rate,customer_avg_delivery_delay,customer_category_diversity,customer_repeat_purchase_indicator
count,99441.000000,99441.000000,98756.000000,99441.000000,96681.000000,96681.000000,99441.000000,99441.000000
mean,1.079223,170.650658,160.659180,4.071235,0.081140,-11.179638,1.017196,0.063777
std,0.396154,235.775976,219.628172,1.346754,0.269906,10.070481,0.259622,0.244356
min,1.000000,0.000000,9.590000,1.000000,0.000000,-146.016123,0.000000,0.000000
25%,1.000000,63.370000,62.690000,4.000000,0.000000,-16.222326,1.000000,0.000000
50%,1.000000,110.200000,106.005000,5.000000,0.000000,-11.787263,1.000000,0.000000
75%,1.000000,188.650000,176.900000,5.000000,0.000000,-6.442685,1.000000,0.000000
max,17.000000,13664.080000,13664.080000,5.000000,1.000000,188.975081,5.000000,1.000000

In [ ]:
print("=" * 70)
print("CUSTOMER SANITY CHECKS")
print("=" * 70)

# ------------------------------------------------------------
# Repeat indicator consistency
# ------------------------------------------------------------

repeat_expected = (
    master_v1["customer_order_count"] > 1
).astype("Int64")

repeat_actual = (
    master_v1[
        "customer_repeat_purchase_indicator"
    ].astype("Int64")
)

repeat_mismatch = (
    repeat_expected != repeat_actual
)

# Ignore rows where customer_order_count is missing
repeat_mismatch = repeat_mismatch[
    master_v1["customer_order_count"].notna()
]

print(
    "Repeat indicator mismatches:",
    repeat_mismatch.sum()
)

# ------------------------------------------------------------
# Total spend should be constant for the same customer
# ------------------------------------------------------------

spend_variation = (
    master_v1
    .dropna(subset=["customer_unique_id"])
    .groupby("customer_unique_id")
    ["customer_total_spend"]
    .nunique()
)

print(
    "Maximum different total-spend values "
    "for one customer:",
    spend_variation.max()
)

# ------------------------------------------------------------
# Order count should be constant for same customer
# ------------------------------------------------------------

order_count_variation = (
    master_v1
    .dropna(subset=["customer_unique_id"])
    .groupby("customer_unique_id")
    ["customer_order_count"]
    .nunique()
)

print(
    "Maximum different order-count values "
    "for one customer:",
    order_count_variation.max()
)

assert repeat_mismatch.sum() == 0
assert spend_variation.max() <= 1
assert order_count_variation.max() <= 1

print("\nAll customer sanity checks passed.")

======================================================================
CUSTOMER SANITY CHECKS
======================================================================
Repeat indicator mismatches: 0
Maximum different total-spend values for one customer: 1
Maximum different order-count values for one customer: 1

All customer sanity checks passed.

In [ ]:
print("=" * 70)
print("FINAL MASTER V1 VALIDATION")
print("=" * 70)

print("Rows:", len(master_v1))
print("Columns:", len(master_v1.columns))
print("Unique order IDs:",
      master_v1["order_id"].nunique())
print("Duplicate order IDs:",
      master_v1["order_id"].duplicated().sum())

assert len(master_v1) == 99441
assert master_v1["order_id"].nunique() == 99441
assert master_v1["order_id"].duplicated().sum() == 0

print("\n" + "=" * 70)
print("DELIVERY PERFORMANCE")
print("=" * 70)

print(
    master_v1["delivery_performance"]
    .value_counts(dropna=False)
)

print("\n" + "=" * 70)
print("CUSTOMER FEATURES")
print("=" * 70)

print(customer_feature_columns)

print("\n" + "=" * 70)
print("PRODUCT FEATURES")
print("=" * 70)

product_feature_columns = [
    "product_category_count",
    "primary_category",
    "product_categories",
    "avg_product_price",
    "min_product_price",
    "max_product_price",
    "total_product_photos",
    "avg_product_photos_qty",
    "avg_product_weight_g",
    "avg_product_volume_cm3",
    "has_multiple_categories"
]

print(product_feature_columns)

print("\n" + "=" * 70)
print("SPEND FEATURES")
print("=" * 70)

spend_feature_columns = [
    "category_identified_spend",
    "category_spend_count",
    "top_spend_category",
    "top_category_spend",
    "top_category_spend_share",
    "category_spend_concentration"
]

print(spend_feature_columns)

======================================================================
FINAL MASTER V1 VALIDATION
======================================================================
Rows: 99441
Columns: 51
Unique order IDs: 99441
Duplicate order IDs: 0

======================================================================
DELIVERY PERFORMANCE
======================================================================
delivery_performance
On Time    88649
Late        7827
<NA>        2965
Name: count, dtype: Int64

======================================================================
CUSTOMER FEATURES
======================================================================
['customer_order_count', 'customer_total_spend', 'customer_avg_order_value', 'customer_avg_review_score', 'customer_late_order_rate', 'customer_avg_delivery_delay', 'customer_category_diversity', 'customer_repeat_purchase_indicator']

======================================================================
PRODUCT FEATURES
======================================================================
['product_category_count', 'primary_category', 'product_categories', 'avg_product_price', 'min_product_price', 'max_product_price', 'total_product_photos', 'avg_product_photos_qty', 'avg_product_weight_g', 'avg_product_volume_cm3', 'has_multiple_categories']

======================================================================
SPEND FEATURES
======================================================================
['category_identified_spend', 'category_spend_count', 'top_spend_category', 'top_category_spend', 'top_category_spend_share', 'category_spend_concentration']

In [ ]:
# ============================================================
# CELL 27 — FINAL MISSING VALUE REPORT
# ============================================================

print("=" * 70)
print("FINAL MASTER V1 — MISSING VALUES")
print("=" * 70)

missing_values = (
    master_v1
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing_values = missing_values[
    missing_values > 0
]

display(missing_values)

======================================================================
FINAL MASTER V1 — MISSING VALUES
======================================================================

order_delivered_customer_date    2965
delivery_delay_days              2965
delivery_days                    2965
delivery_performance             2965
customer_late_order_rate         2760
customer_avg_delivery_delay      2760
category_identified_spend        2185
primary_category                 2185
product_categories               2185
top_spend_category               2185
top_category_spend               2185
category_spend_concentration     2185
top_category_spend_share         2185
category_spend_count             2185
avg_product_photos_qty           2164
order_delivered_carrier_date     1783
avg_product_volume_cm3            791
avg_product_weight_g              791
unique_products                   775
has_multiple_categories           775
avg_product_price                 775
min_product_price                 775
total_product_photos              775
product_category_count            775
max_product_price                 775
order_value                       775
unique_sellers                    775
item_count                        775
freight_value                     775
product_value                     775
customer_avg_order_value          685
order_approved_at                 160
payment_count                       1
max_installments                    1
total_payment_value                 1
dtype: int64

In [ ]:
print("=" * 70)
print("FINAL MASTER V1 — COLUMNS")
print("=" * 70)

for i, column in enumerate(
    master_v1.columns,
    start=1
):
    print(f"{i:2d}. {column}")

print("\nTotal columns:",
      len(master_v1.columns))

======================================================================
FINAL MASTER V1 — COLUMNS
======================================================================
 1. order_id
 2. customer_id
 3. order_status
 4. order_purchase_timestamp
 5. order_approved_at
 6. order_delivered_carrier_date
 7. order_delivered_customer_date
 8. order_estimated_delivery_date
 9. item_count
10. unique_products
11. unique_sellers
12. product_value
13. freight_value
14. order_value
15. total_payment_value
16. payment_count
17. max_installments
18. review_count
19. review_score_mean
20. review_score_min
21. review_score_max
22. delivery_days
23. estimated_delivery_days
24. delivery_delay_days
25. delivery_performance
26. product_category_count
27. primary_category
28. product_categories
29. avg_product_price
30. min_product_price
31. max_product_price
32. total_product_photos
33. avg_product_photos_qty
34. avg_product_weight_g
35. avg_product_volume_cm3
36. has_multiple_categories
37. category_identified_spend
38. category_spend_count
39. top_spend_category
40. top_category_spend
41. top_category_spend_share
42. category_spend_concentration
43. customer_unique_id
44. customer_order_count
45. customer_total_spend
46. customer_avg_order_value
47. customer_avg_review_score
48. customer_late_order_rate
49. customer_avg_delivery_delay
50. customer_category_diversity
51. customer_repeat_purchase_indicator

Total columns: 51

In [ ]:

print("=" * 70)
print("FINAL MASTER V1 — SAMPLE")
print("=" * 70)

display(
    master_v1.head(10)
)

======================================================================
FINAL MASTER V1 — SAMPLE
======================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,item_count,unique_products,unique_sellers,product_value,freight_value,order_value,total_payment_value,payment_count,max_installments,review_count,review_score_mean,review_score_min,review_score_max,delivery_days,estimated_delivery_days,delivery_delay_days,delivery_performance,product_category_count,primary_category,product_categories,avg_product_price,min_product_price,max_product_price,total_product_photos,avg_product_photos_qty,avg_product_weight_g,avg_product_volume_cm3,has_multiple_categories,category_identified_spend,category_spend_count,top_spend_category,top_category_spend,top_category_spend_share,category_spend_concentration,customer_unique_id,customer_order_count,customer_total_spend,customer_avg_order_value,customer_avg_review_score,customer_late_order_rate,customer_avg_delivery_delay,customer_category_diversity,customer_repeat_purchase_indicator
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,1.0,1.0,29.99,8.72,38.71,38.71,3.0,1.0,1,4.0,4,4,8.436574,15.544063,-7.107488,On Time,1.0,housewares,housewares,29.99,29.99,29.99,4.0,4.0,500.0,1976.0,False,29.99,1.0,housewares,29.99,1.0,1.0,7c396fd4830fd04220f754e42b4e5bff,2,82.82,41.41,4.5,0.0,-8.150851,2,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1.0,1.0,1.0,118.70,22.76,141.46,141.46,1.0,1.0,1,4.0,4,4,13.782037,19.137766,-5.355729,On Time,1.0,perfumery,perfumery,118.70,118.70,118.70,1.0,1.0,400.0,4693.0,False,118.70,1.0,perfumery,118.70,1.0,1.0,af07308b275d755c9edb36a90c618231,1,141.46,141.46,4.0,0.0,-5.355729,1,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1.0,1.0,1.0,159.90,19.22,179.12,179.12,1.0,3.0,1,5.0,5,5,9.394213,26.639711,-17.245498,On Time,1.0,auto,auto,159.90,159.90,159.90,1.0,1.0,420.0,9576.0,False,159.90,1.0,auto,159.90,1.0,1.0,3a653a41f6f9fc3d2a113cf8398680e8,1,179.12,179.12,5.0,0.0,-17.245498,1,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1.0,1.0,1.0,45.00,27.20,72.20,72.20,1.0,1.0,1,5.0,5,5,13.208750,26.188819,-12.980069,On Time,1.0,pet_shop,pet_shop,45.00,45.00,45.00,3.0,3.0,450.0,6000.0,False,45.00,1.0,pet_shop,45.00,1.0,1.0,7c142cf63193a1473d2e66489a9ae977,1,72.20,72.20,5.0,0.0,-12.980069,1,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1.0,1.0,1.0,19.90,8.72,28.62,28.62,1.0,1.0,1,5.0,5,5,2.873877,12.112049,-9.238171,On Time,1.0,stationery,stationery,19.90,19.90,19.90,4.0,4.0,250.0,11475.0,False,19.90,1.0,stationery,19.90,1.0,1.0,72632f0f9dd73dfee390c9b22eb56dd6,1,28.62,28.62,5.0,0.0,-9.238171,1,0
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,1.0,1.0,1.0,147.90,27.36,175.26,175.26,1.0,6.0,1,4.0,4,4,16.542245,22.085359,-5.543113,On Time,1.0,auto,auto,147.90,147.90,147.90,1.0,1.0,7150.0,42250.0,False,147.90,1.0,auto,147.90,1.0,1.0,80bb27c7c16e8f973207a5086ab329e2,1,175.26,175.26,4.0,0.0,-5.543113,1,0
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09,1.0,1.0,1.0,49.90,16.05,65.95,65.95,1.0,1.0,1,2.0,2,2,NaN,27.484630,NaN,<NA>,0.0,<NA>,<NA>,49.90,49.90,49.90,0.0,NaN,600.0,18375.0,False,NaN,NaN,NaN,NaN,NaN,NaN,36edbb3fb164b1f16485364b6fb04c73,1,65.95,65.95,2.0,NaN,NaN,0,0
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,1.0,1.0,1.0,59.99,15.17,75.16,75.16,1.0,3.0,1,5.0,5,5,9.989826,21.451042,-11.461215,On Time,1.0,auto,auto,59.99,59.99,59.99,1.0,1.0,50.0,4352.0,False,59.99,1.0,auto,59.99,1.0,1.0,932afa1e708222e5821dac9cd5db4cae,1,75.16,75.16,5.0,0.0,-11.461215,1,0
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06,1.0,1.0,1.0,19.90,16.05,35.95,35.95,1.0,1.0,1,1.0,1,1,9.818762,41.229757,-31.410995,On Time,1.0,furniture_decor,furniture_decor,19.90,19.90,19.90,2.0,2.0,300.0,18375.0,False,19.90,1.0,furniture_decor,19.90,1.0,1.0,39382392765b6dc74812866ee5ee92a7,1,35.95,35.95,1.0,0.0,-31.410995,1,0
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,1.0,1.0,1.0,149.99,19.77,169.76,169.76,2.0,1.0,1,5.0,5,5,18.221852,24.503449,-6.281597,On Time,1.0,office_furniture,office_furniture,149.99,149.99,149.99,1.0,1.0,9750.0,72324.0,False,149.99,1.0,office_furniture,149.99,1.0,1.0,299905e3934e9e181bfb2e164dd4b4f8,1,169.76,169.76,5.0,0.0,-6.281597,1,0

In [ ]:
print("=" * 70)
print("SAVING FINAL MASTER V1")
print("=" * 70)

OUTPUT_FILE = "master_v1_phase1_complete.csv"

master_v1.to_csv(
    OUTPUT_FILE,
    index=False
)

print("SUCCESS")
print()
print("File:", OUTPUT_FILE)
print("Rows:", len(master_v1))
print("Columns:", len(master_v1.columns))
print("Unique orders:",
      master_v1["order_id"].nunique())
print("Duplicate orders:",
      master_v1["order_id"].duplicated().sum())

======================================================================
SAVING FINAL MASTER V1
======================================================================
SUCCESS

File: master_v1_phase1_complete.csv
Rows: 99441
Columns: 51
Unique orders: 99441
Duplicate orders: 0

In [ ]:
print("=" * 70)
print("PHASE 1 — FINAL SUCCESS CHECK")
print("=" * 70)

checks = {
    "99,441 rows":
        len(master_v1) == 99441,

    "99,441 unique orders":
        master_v1["order_id"].nunique() == 99441,

    "Zero duplicate orders":
        master_v1["order_id"].duplicated().sum() == 0,

    "Customer features exist":
        all(
            col in master_v1.columns
            for col in customer_feature_columns
        ),

    "Product features exist":
        all(
            col in master_v1.columns
            for col in product_feature_columns
        ),

    "Spend features exist":
        all(
            col in master_v1.columns
            for col in spend_feature_columns
        )
}

for check, result in checks.items():
    print(
        "✓" if result else "✗",
        check
    )

assert all(checks.values())

print()
print("=" * 70)
print("SUCCESS — PHASE 1 COMPLETE")
print("=" * 70)

print()
print("Final file:")
print("master_v1_phase1_complete.csv")

print()
print("Final shape:")
print(master_v1.shape)

======================================================================
PHASE 1 — FINAL SUCCESS CHECK
======================================================================
✓ 99,441 rows
✓ 99,441 unique orders
✓ Zero duplicate orders
✓ Customer features exist
✓ Product features exist
✓ Spend features exist

======================================================================
SUCCESS — PHASE 1 COMPLETE
======================================================================

Final file:
master_v1_phase1_complete.csv

Final shape:
(99441, 51)

In [ ]:
# ============================================================
# CHECK ORDERS WITH MISSING ITEM INFORMATION
# ============================================================

item_missing_cols = [
    "item_count",
    "unique_products",
    "unique_sellers",
    "product_value",
    "freight_value",
    "order_value"
]

missing_item_orders = master_v1[
    master_v1[item_missing_cols].isna().all(axis=1)
]

print("=" * 70)
print("ORDERS WITH NO ITEM-LEVEL INFORMATION")
print("=" * 70)

print("Number of orders:", len(missing_item_orders))
print("Expected:", 775)

print("\nOrder status distribution:")
print(missing_item_orders["order_status"].value_counts(dropna=False))

print("\nSample:")
display(
    missing_item_orders[
        [
            "order_id",
            "order_status",
            "order_purchase_timestamp",
            "order_approved_at",
            "order_delivered_customer_date",
            "order_value"
        ]
    ].head(10)
)

======================================================================
ORDERS WITH NO ITEM-LEVEL INFORMATION
======================================================================
Number of orders: 775
Expected: 775

Order status distribution:
order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

Sample:

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_customer_date,order_value
266,8e24261a7e58791d10cb1bf9da94df5c,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaT,NaN
586,c272bcd21c287498b4883c7512019702,unavailable,2018-01-31 11:31:37,2018-01-31 14:23:50,NaT,NaN
687,37553832a3a89c9b2db59701c357ca67,unavailable,2017-08-14 17:38:02,2017-08-17 00:15:18,NaT,NaN
737,d57e15fb07fd180f06ab3926b39edcd2,unavailable,2018-01-08 19:39:03,2018-01-09 07:26:08,NaT,NaN
1130,00b1cb0320190ca0daa2c88b35206009,canceled,2018-08-28 15:26:39,NaT,NaT,NaN
1160,2f634e2cebf8c0283e7ef0989f77d217,unavailable,2017-09-27 20:55:33,2017-09-28 01:32:50,NaT,NaN
1579,ee0db22a8e742b752914016708470ec8,unavailable,2017-08-24 11:04:41,2017-08-24 11:15:11,NaT,NaN
1801,ed3efbd3a87bea76c2812c66a0b32219,canceled,2018-09-20 13:54:16,NaT,NaT,NaN
1826,6ad57aecbae806a7e9cc2cdb6b380711,unavailable,2017-11-30 07:48:24,2017-11-30 08:14:42,NaT,NaN
1868,df8282afe61008dc26c6c31011474d02,canceled,2017-03-04 12:14:30,NaT,NaT,NaN

In [ ]:
# ============================================================
# CELL 1 — LOAD COMPLETED PHASE 1 DATASET
# ============================================================

import pandas as pd
import numpy as np

INPUT_FILE = "master_v1_phase1_complete.csv"

master_v1 = pd.read_csv(INPUT_FILE)

print("=" * 70)
print("PHASE 1 DATASET LOADED")
print("=" * 70)

print("File:", INPUT_FILE)
print("Rows:", len(master_v1))
print("Columns:", len(master_v1.columns))
print("Unique order IDs:", master_v1["order_id"].nunique())
print("Duplicate order IDs:", master_v1["order_id"].duplicated().sum())

======================================================================
PHASE 1 DATASET LOADED
======================================================================
File: master_v1_phase1_complete.csv
Rows: 99441
Columns: 51
Unique order IDs: 99441
Duplicate order IDs: 0

In [ ]:
# ============================================================
# CELL 2 — CHECK CURRENT PHASE 1 COLUMNS
# ============================================================

print("=" * 70)
print("CURRENT DATASET COLUMNS")
print("=" * 70)

for i, col in enumerate(master_v1.columns, start=1):
    print(f"{i:2}. {col}")

print("\nTotal columns:", len(master_v1.columns))

======================================================================
CURRENT DATASET COLUMNS
======================================================================
 1. order_id
 2. customer_id
 3. order_status
 4. order_purchase_timestamp
 5. order_approved_at
 6. order_delivered_carrier_date
 7. order_delivered_customer_date
 8. order_estimated_delivery_date
 9. item_count
10. unique_products
11. unique_sellers
12. product_value
13. freight_value
14. order_value
15. total_payment_value
16. payment_count
17. max_installments
18. review_count
19. review_score_mean
20. review_score_min
21. review_score_max
22. delivery_days
23. estimated_delivery_days
24. delivery_delay_days
25. delivery_performance
26. product_category_count
27. primary_category
28. product_categories
29. avg_product_price
30. min_product_price
31. max_product_price
32. total_product_photos
33. avg_product_photos_qty
34. avg_product_weight_g
35. avg_product_volume_cm3
36. has_multiple_categories
37. category_identified_spend
38. category_spend_count
39. top_spend_category
40. top_category_spend
41. top_category_spend_share
42. category_spend_concentration
43. customer_unique_id
44. customer_order_count
45. customer_total_spend
46. customer_avg_order_value
47. customer_avg_review_score
48. customer_late_order_rate
49. customer_avg_delivery_delay
50. customer_category_diversity
51. customer_repeat_purchase_indicator

Total columns: 51

In [ ]:
# ============================================================
# CELL 3 — CHECK WHICH ENRICHMENTS ALREADY EXIST
# ============================================================

product_features = [
    "product_category_count",
    "primary_category",
    "product_categories",
    "avg_product_price",
    "avg_product_photos_qty",
    "avg_product_weight_g",
    "avg_product_volume_cm3",
    "total_product_photos",
    "has_multiple_categories"
]

spend_features = [
    "category_identified_spend",
    "category_spend_count",
    "top_spend_category",
    "top_category_spend",
    "top_category_spend_share",
    "category_spend_concentration"
]

customer_features = [
    "customer_order_count",
    "customer_total_spend",
    "customer_avg_order_value",
    "customer_avg_review_score",
    "customer_late_order_rate",
    "customer_avg_delivery_delay",
    "customer_category_diversity",
    "customer_repeat_purchase_indicator"
]

print("=" * 70)
print("ENRICHMENT STATUS")
print("=" * 70)

print("\nPRODUCT/CATEGORY FEATURES:")
for col in product_features:
    print(("✓ " if col in master_v1.columns else "✗ "), col)

print("\nSPEND FEATURES:")
for col in spend_features:
    print(("✓ " if col in master_v1.columns else "✗ "), col)

print("\nCUSTOMER FEATURES:")
for col in customer_features:
    print(("✓ " if col in master_v1.columns else "✗ "), col)

======================================================================
ENRICHMENT STATUS
======================================================================

PRODUCT/CATEGORY FEATURES:
✓  product_category_count
✓  primary_category
✓  product_categories
✓  avg_product_price
✓  avg_product_photos_qty
✓  avg_product_weight_g
✓  avg_product_volume_cm3
✓  total_product_photos
✓  has_multiple_categories

SPEND FEATURES:
✓  category_identified_spend
✓  category_spend_count
✓  top_spend_category
✓  top_category_spend
✓  top_category_spend_share
✓  category_spend_concentration

CUSTOMER FEATURES:
✓  customer_order_count
✓  customer_total_spend
✓  customer_avg_order_value
✓  customer_avg_review_score
✓  customer_late_order_rate
✓  customer_avg_delivery_delay
✓  customer_category_diversity
✓  customer_repeat_purchase_indicator

In [ ]:
print("=" * 70)
print("ORDER-LEVEL GRAIN VALIDATION")
print("=" * 70)

total_rows = len(master_v1)
unique_orders = master_v1["order_id"].nunique()
duplicate_orders = master_v1["order_id"].duplicated().sum()

print("Total rows:", total_rows)
print("Unique order IDs:", unique_orders)
print("Duplicate order IDs:", duplicate_orders)

if total_rows == unique_orders and duplicate_orders == 0:
    print("\n✓ PASS — One row per order is preserved.")
else:
    print("\n✗ FAIL — Order-level grain has been violated.")

======================================================================
ORDER-LEVEL GRAIN VALIDATION
======================================================================
Total rows: 99441
Unique order IDs: 99441
Duplicate order IDs: 0

✓ PASS — One row per order is preserved.

In [ ]:
print("=" * 70)
print("MASTER V1 — MISSING VALUE CHECK")
print("=" * 70)

missing = master_v1.isna().sum()

missing = missing[missing > 0].sort_values(ascending=False)

if len(missing) == 0:
    print("✓ No missing values found.")
else:
    print("Columns containing missing values:\n")
    print(missing)

print("\nTotal missing cells:", int(master_v1.isna().sum().sum()))

======================================================================
MASTER V1 — MISSING VALUE CHECK
======================================================================
Columns containing missing values:

order_delivered_customer_date    2965
delivery_performance             2965
delivery_delay_days              2965
delivery_days                    2965
customer_avg_delivery_delay      2760
customer_late_order_rate         2760
top_category_spend               2185
top_category_spend_share         2185
category_identified_spend        2185
product_categories               2185
primary_category                 2185
category_spend_concentration     2185
top_spend_category               2185
category_spend_count             2185
avg_product_photos_qty           2164
order_delivered_carrier_date     1783
avg_product_weight_g              791
avg_product_volume_cm3            791
unique_products                   775
has_multiple_categories           775
unique_sellers                    775
item_count                        775
avg_product_price                 775
freight_value                     775
order_value                       775
product_category_count            775
product_value                     775
max_product_price                 775
min_product_price                 775
total_product_photos              775
customer_avg_order_value          685
order_approved_at                 160
max_installments                    1
total_payment_value                 1
payment_count                       1
dtype: int64

Total missing cells: 50537

In [ ]:
print("=" * 70)
print("CUSTOMER ENRICHMENT VALIDATION")
print("=" * 70)

customer_cols = [
    "customer_unique_id",
    "customer_order_count",
    "customer_total_spend",
    "customer_avg_order_value",
    "customer_avg_review_score",
    "customer_late_order_rate",
    "customer_avg_delivery_delay",
    "customer_category_diversity",
    "customer_repeat_purchase_indicator"
]

# ------------------------------------------------------------
# 1. Missing customer_unique_id
# ------------------------------------------------------------

missing_customer_id = master_v1["customer_unique_id"].isna().sum()

print("\n[1] CUSTOMER UNIQUE ID")
print("Missing customer_unique_id:", missing_customer_id)
print(
    "Missing percentage:",
    round(missing_customer_id / len(master_v1) * 100, 2),
    "%"
)

# ------------------------------------------------------------
# 2. Customer feature missingness
# ------------------------------------------------------------

print("\n[2] CUSTOMER FEATURE MISSINGNESS")

for col in customer_cols[1:]:
    missing_count = master_v1[col].isna().sum()

    print(
        f"{col:40} | Missing: {missing_count}"
    )

# ------------------------------------------------------------
# 3. Check whether missing customer IDs have
#    customer-level values
# ------------------------------------------------------------

print("\n[3] MISSING CUSTOMER ID → CUSTOMER FEATURES")

missing_id_mask = master_v1["customer_unique_id"].isna()

if missing_id_mask.sum() > 0:

    for col in customer_cols[1:]:

        populated = master_v1.loc[
            missing_id_mask, col
        ].notna().sum()

        print(
            f"{col:40} | "
            f"Populated despite missing ID: {populated}"
        )

else:
    print("No missing customer_unique_id values.")

# ------------------------------------------------------------
# 4. Final interpretation
# ------------------------------------------------------------

print("\n[4] INTERPRETATION")

misleading_features = 0

if missing_id_mask.sum() > 0:

    for col in customer_cols[1:]:

        populated = master_v1.loc[
            missing_id_mask, col
        ].notna().sum()

        misleading_features += populated

if misleading_features == 0:
    print(
        "✓ PASS — No customer-level features are populated "
        "for rows with missing customer_unique_id."
    )
else:
    print(
        "⚠ REVIEW — Some customer-level features are populated "
        "despite missing customer_unique_id."
    )
    print(
        "Total potentially misleading populated values:",
        misleading_features
    )

======================================================================
CUSTOMER ENRICHMENT VALIDATION
======================================================================

[1] CUSTOMER UNIQUE ID
Missing customer_unique_id: 0
Missing percentage: 0.0 %

[2] CUSTOMER FEATURE MISSINGNESS
customer_order_count                     | Missing: 0
customer_total_spend                     | Missing: 0
customer_avg_order_value                 | Missing: 685
customer_avg_review_score                | Missing: 0
customer_late_order_rate                 | Missing: 2760
customer_avg_delivery_delay              | Missing: 2760
customer_category_diversity              | Missing: 0
customer_repeat_purchase_indicator       | Missing: 0

[3] MISSING CUSTOMER ID → CUSTOMER FEATURES
No missing customer_unique_id values.

[4] INTERPRETATION
✓ PASS — No customer-level features are populated for rows with missing customer_unique_id.

In [ ]:
print("=" * 70)
print("FINANCIAL & NUMERICAL RANGE VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# 1. Financial columns
# ------------------------------------------------------------

financial_cols = [
    "product_value",
    "freight_value",
    "order_value",
    "total_payment_value",
    "avg_product_price",
    "min_product_price",
    "max_product_price",
    "category_identified_spend",
    "top_category_spend"
]

print("\n[1] FINANCIAL FEATURES")
print("-" * 70)

for col in financial_cols:

    if col not in master_v1.columns:
        print(f"{col:35} | COLUMN NOT FOUND")
        continue

    series = master_v1[col].dropna()

    if len(series) == 0:
        print(f"{col:35} | No valid values")
        continue

    negative_count = (series < 0).sum()

    print(
        f"{col:35} | "
        f"Min: {series.min():.2f} | "
        f"Max: {series.max():.2f} | "
        f"Negative: {negative_count}"
    )


# ------------------------------------------------------------
# 2. Review score validation
# ------------------------------------------------------------

print("\n[2] REVIEW SCORE VALIDATION")
print("-" * 70)

review_series = master_v1["review_score_mean"].dropna()

invalid_review_scores = (
    (review_series < 1) |
    (review_series > 5)
).sum()

print("Minimum review score:", review_series.min())
print("Maximum review score:", review_series.max())
print("Invalid review scores:", invalid_review_scores)


# ------------------------------------------------------------
# 3. Late order rate validation
# ------------------------------------------------------------

print("\n[3] CUSTOMER LATE ORDER RATE")
print("-" * 70)

late_rate = master_v1["customer_late_order_rate"].dropna()

invalid_late_rates = (
    (late_rate < 0) |
    (late_rate > 1)
).sum()

print("Minimum late order rate:", late_rate.min())
print("Maximum late order rate:", late_rate.max())
print("Invalid late order rates:", invalid_late_rates)


# ------------------------------------------------------------
# 4. Repeat purchase indicator
# ------------------------------------------------------------

print("\n[4] REPEAT PURCHASE INDICATOR")
print("-" * 70)

print(
    master_v1[
        "customer_repeat_purchase_indicator"
    ].value_counts(dropna=False)
)

invalid_repeat = (
    ~master_v1[
        "customer_repeat_purchase_indicator"
    ].dropna().isin([0, 1])
).sum()

print("Invalid repeat purchase values:", invalid_repeat)


# ------------------------------------------------------------
# 5. Delivery delay validation
# ------------------------------------------------------------

print("\n[5] DELIVERY DELAY")
print("-" * 70)

delay = master_v1["delivery_delay_days"].dropna()

print("Minimum delivery delay:", delay.min())
print("Maximum delivery delay:", delay.max())
print("Average delivery delay:", round(delay.mean(), 2))

print(
    "Rows with negative delay:",
    (delay < 0).sum()
)


# ------------------------------------------------------------
# FINAL RESULT
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RANGE VALIDATION COMPLETE")
print("=" * 70)

if (
    invalid_review_scores == 0
    and invalid_late_rates == 0
    and invalid_repeat == 0
):
    print("✓ PASS — Core numerical ranges are valid.")
else:
    print("⚠ REVIEW — One or more numerical range checks failed.")

======================================================================
FINANCIAL & NUMERICAL RANGE VALIDATION
======================================================================

[1] FINANCIAL FEATURES
----------------------------------------------------------------------
product_value                       | Min: 0.85 | Max: 13440.00 | Negative: 0
freight_value                       | Min: 0.00 | Max: 1794.96 | Negative: 0
order_value                         | Min: 9.59 | Max: 13664.08 | Negative: 0
total_payment_value                 | Min: 0.00 | Max: 13664.08 | Negative: 0
avg_product_price                   | Min: 0.85 | Max: 6735.00 | Negative: 0
min_product_price                   | Min: 0.85 | Max: 6735.00 | Negative: 0
max_product_price                   | Min: 0.85 | Max: 6735.00 | Negative: 0
category_identified_spend           | Min: 0.85 | Max: 13440.00 | Negative: 0
top_category_spend                  | Min: 0.85 | Max: 13440.00 | Negative: 0

[2] REVIEW SCORE VALIDATION
----------------------------------------------------------------------
Minimum review score: 1.0
Maximum review score: 5.0
Invalid review scores: 0

[3] CUSTOMER LATE ORDER RATE
----------------------------------------------------------------------
Minimum late order rate: 0.0
Maximum late order rate: 1.0
Invalid late order rates: 0

[4] REPEAT PURCHASE INDICATOR
----------------------------------------------------------------------
customer_repeat_purchase_indicator
0    93099
1     6342
Name: count, dtype: int64
Invalid repeat purchase values: 0

[5] DELIVERY DELAY
----------------------------------------------------------------------
Minimum delivery delay: -146.0161226851852
Maximum delivery delay: 188.97508101851847
Average delivery delay: -11.18
Rows with negative delay: 88649

======================================================================
RANGE VALIDATION COMPLETE
======================================================================
✓ PASS — Core numerical ranges are valid.

In [ ]:
print("=" * 70)
print("DELIVERY & ORDER STATUS CONSISTENCY CHECK")
print("=" * 70)

# ------------------------------------------------------------
# 1. Order status distribution
# ------------------------------------------------------------

print("\n[1] ORDER STATUS DISTRIBUTION")
print("-" * 70)

print(
    master_v1["order_status"]
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 2. Delivery performance distribution
# ------------------------------------------------------------

print("\n[2] DELIVERY PERFORMANCE DISTRIBUTION")
print("-" * 70)

print(
    master_v1["delivery_performance"]
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 3. Delivered orders should have delivery date
# ------------------------------------------------------------

print("\n[3] DELIVERED ORDERS WITHOUT DELIVERY DATE")
print("-" * 70)

delivered_mask = (
    master_v1["order_status"].str.lower() == "delivered"
)

delivered_without_date = (
    delivered_mask &
    master_v1["order_delivered_customer_date"].isna()
).sum()

print(
    "Delivered orders:",
    delivered_mask.sum()
)

print(
    "Delivered orders missing customer delivery date:",
    delivered_without_date
)


# ------------------------------------------------------------
# 4. Undelivered orders with delivery performance
# ------------------------------------------------------------

print("\n[4] NON-DELIVERED ORDERS WITH DELIVERY PERFORMANCE")
print("-" * 70)

non_delivered_mask = ~delivered_mask

non_delivered_with_performance = (
    non_delivered_mask &
    master_v1["delivery_performance"].notna()
).sum()

print(
    "Non-delivered orders:",
    non_delivered_mask.sum()
)

print(
    "Non-delivered orders with delivery performance:",
    non_delivered_with_performance
)


# ------------------------------------------------------------
# 5. Delivered orders missing delivery days
# ------------------------------------------------------------

print("\n[5] DELIVERED ORDERS MISSING DELIVERY DAYS")
print("-" * 70)

delivered_missing_days = (
    delivered_mask &
    master_v1["delivery_days"].isna()
).sum()

print(
    "Delivered orders missing delivery_days:",
    delivered_missing_days
)


# ------------------------------------------------------------
# 6. Delivery performance vs delay
# ------------------------------------------------------------

print("\n[6] DELIVERY PERFORMANCE VS DELIVERY DELAY")
print("-" * 70)

performance_check = master_v1[
    master_v1["delivery_performance"].notna() &
    master_v1["delivery_delay_days"].notna()
].copy()

if len(performance_check) > 0:

    # On Time should correspond to delay <= 0
    on_time_wrong = (
        (performance_check["delivery_performance"] == "On Time") &
        (performance_check["delivery_delay_days"] > 0)
    ).sum()

    # Late should correspond to delay > 0
    late_wrong = (
        (performance_check["delivery_performance"] == "Late") &
        (performance_check["delivery_delay_days"] <= 0)
    ).sum()

    print(
        "On Time orders with positive delay:",
        on_time_wrong
    )

    print(
        "Late orders with zero/negative delay:",
        late_wrong
    )

else:
    on_time_wrong = 0
    late_wrong = 0
    print("No valid delivery records available for comparison.")


# ------------------------------------------------------------
# 7. Final interpretation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DELIVERY CONSISTENCY RESULT")
print("=" * 70)

issues = (
    delivered_without_date +
    non_delivered_with_performance +
    delivered_missing_days +
    on_time_wrong +
    late_wrong
)

if issues == 0:
    print("✓ PASS — Delivery fields are internally consistent.")
else:
    print(
        "⚠ REVIEW —",
        issues,
        "potential delivery consistency issues found."
    )

======================================================================
DELIVERY & ORDER STATUS CONSISTENCY CHECK
======================================================================

[1] ORDER STATUS DISTRIBUTION
----------------------------------------------------------------------
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

[2] DELIVERY PERFORMANCE DISTRIBUTION
----------------------------------------------------------------------
delivery_performance
On Time    88649
Late        7827
NaN         2965
Name: count, dtype: int64

[3] DELIVERED ORDERS WITHOUT DELIVERY DATE
----------------------------------------------------------------------
Delivered orders: 96478
Delivered orders missing customer delivery date: 8

[4] NON-DELIVERED ORDERS WITH DELIVERY PERFORMANCE
----------------------------------------------------------------------
Non-delivered orders: 2963
Non-delivered orders with delivery performance: 6

[5] DELIVERED ORDERS MISSING DELIVERY DAYS
----------------------------------------------------------------------
Delivered orders missing delivery_days: 8

[6] DELIVERY PERFORMANCE VS DELIVERY DELAY
----------------------------------------------------------------------
On Time orders with positive delay: 0
Late orders with zero/negative delay: 0

======================================================================
DELIVERY CONSISTENCY RESULT
======================================================================
⚠ REVIEW — 22 potential delivery consistency issues found.

In [ ]:
print("=" * 70)
print("PRODUCT, CATEGORY & SPEND CONSISTENCY CHECK")
print("=" * 70)

# ------------------------------------------------------------
# 1. Product/category feature availability
# ------------------------------------------------------------

print("\n[1] PRODUCT/CATEGORY FEATURE COVERAGE")
print("-" * 70)

product_cols = [
    "item_count",
    "unique_products",
    "unique_sellers",
    "product_value",
    "freight_value",
    "order_value",
    "product_category_count",
    "primary_category",
    "avg_product_price"
]

for col in product_cols:
    missing = master_v1[col].isna().sum()
    available = master_v1[col].notna().sum()

    print(
        f"{col:35} | "
        f"Available: {available:6} | "
        f"Missing: {missing:6}"
    )


# ------------------------------------------------------------
# 2. Product count consistency
# ------------------------------------------------------------

print("\n[2] PRODUCT COUNT CONSISTENCY")
print("-" * 70)

product_count_issue = (
    master_v1["unique_products"].notna() &
    master_v1["item_count"].notna() &
    (master_v1["unique_products"] > master_v1["item_count"])
).sum()

print(
    "Orders where unique_products > item_count:",
    product_count_issue
)


# ------------------------------------------------------------
# 3. Seller count consistency
# ------------------------------------------------------------

print("\n[3] SELLER COUNT CONSISTENCY")
print("-" * 70)

seller_count_issue = (
    master_v1["unique_sellers"].notna() &
    master_v1["item_count"].notna() &
    (master_v1["unique_sellers"] > master_v1["item_count"])
).sum()

print(
    "Orders where unique_sellers > item_count:",
    seller_count_issue
)


# ------------------------------------------------------------
# 4. Category count consistency
# ------------------------------------------------------------

print("\n[4] CATEGORY COUNT CONSISTENCY")
print("-" * 70)

category_count_issue = (
    master_v1["product_category_count"].notna() &
    master_v1["item_count"].notna() &
    (
        master_v1["product_category_count"]
        > master_v1["item_count"]
    )
).sum()

print(
    "Orders where category count > item count:",
    category_count_issue
)


# ------------------------------------------------------------
# 5. Spend consistency
# ------------------------------------------------------------

print("\n[5] CATEGORY SPEND CONSISTENCY")
print("-" * 70)

spend_issue = (
    master_v1["category_identified_spend"].notna() &
    master_v1["order_value"].notna() &
    (
        master_v1["category_identified_spend"]
        > master_v1["order_value"] + 0.01
    )
).sum()

print(
    "Orders where identified category spend > order value:",
    spend_issue
)


# ------------------------------------------------------------
# 6. Top category spend share
# ------------------------------------------------------------

print("\n[6] TOP CATEGORY SPEND SHARE")
print("-" * 70)

share = master_v1["top_category_spend_share"].dropna()

invalid_share = (
    (share < 0) |
    (share > 1)
).sum()

print("Minimum share:", share.min())
print("Maximum share:", share.max())
print("Invalid shares:", invalid_share)


# ------------------------------------------------------------
# 7. Multiple category indicator
# ------------------------------------------------------------

print("\n[7] MULTIPLE CATEGORY VALIDATION")
print("-" * 70)

multi_category = master_v1[
    master_v1["has_multiple_categories"].notna() &
    master_v1["product_category_count"].notna()
].copy()

multiple_category_issue = (
    (
        multi_category["has_multiple_categories"] == True
    ) &
    (
        multi_category["product_category_count"] <= 1
    )
).sum()

single_category_issue = (
    (
        multi_category["has_multiple_categories"] == False
    ) &
    (
        multi_category["product_category_count"] > 1
    )
).sum()

print(
    "Multiple-category flag = True but category count <= 1:",
    multiple_category_issue
)

print(
    "Multiple-category flag = False but category count > 1:",
    single_category_issue
)


# ------------------------------------------------------------
# FINAL RESULT
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PRODUCT & SPEND CONSISTENCY RESULT")
print("=" * 70)

total_issues = (
    product_count_issue
    + seller_count_issue
    + category_count_issue
    + spend_issue
    + invalid_share
    + multiple_category_issue
    + single_category_issue
)

if total_issues == 0:
    print("✓ PASS — Product/category/spend features are consistent.")
else:
    print(
        "⚠ REVIEW —",
        total_issues,
        "potential product/category/spend issues found."
    )

======================================================================
PRODUCT, CATEGORY & SPEND CONSISTENCY CHECK
======================================================================

[1] PRODUCT/CATEGORY FEATURE COVERAGE
----------------------------------------------------------------------
item_count                          | Available:  98666 | Missing:    775
unique_products                     | Available:  98666 | Missing:    775
unique_sellers                      | Available:  98666 | Missing:    775
product_value                       | Available:  98666 | Missing:    775
freight_value                       | Available:  98666 | Missing:    775
order_value                         | Available:  98666 | Missing:    775
product_category_count              | Available:  98666 | Missing:    775
primary_category                    | Available:  97256 | Missing:   2185
avg_product_price                   | Available:  98666 | Missing:    775

[2] PRODUCT COUNT CONSISTENCY
----------------------------------------------------------------------
Orders where unique_products > item_count: 0

[3] SELLER COUNT CONSISTENCY
----------------------------------------------------------------------
Orders where unique_sellers > item_count: 0

[4] CATEGORY COUNT CONSISTENCY
----------------------------------------------------------------------
Orders where category count > item count: 0

[5] CATEGORY SPEND CONSISTENCY
----------------------------------------------------------------------
Orders where identified category spend > order value: 0

[6] TOP CATEGORY SPEND SHARE
----------------------------------------------------------------------
Minimum share: 0.3431513409961686
Maximum share: 1.0
Invalid shares: 0

[7] MULTIPLE CATEGORY VALIDATION
----------------------------------------------------------------------
Multiple-category flag = True but category count <= 1: 0
Multiple-category flag = False but category count > 1: 0

======================================================================
PRODUCT & SPEND CONSISTENCY RESULT
======================================================================
✓ PASS — Product/category/spend features are consistent.

In [ ]:
import pandas as pd
import numpy as np

INPUT_FILE = "master_v1_phase1_complete.csv"

master_v1 = pd.read_csv(INPUT_FILE)

print("=" * 70)
print("CUSTOMER ENRICHMENT CONSISTENCY CHECK")
print("=" * 70)

print(f"Rows: {len(master_v1):,}")
print(f"Unique orders: {master_v1['order_id'].nunique():,}")
print(f"Duplicate orders: {master_v1['order_id'].duplicated().sum():,}")

======================================================================
CUSTOMER ENRICHMENT CONSISTENCY CHECK
======================================================================
Rows: 99,441
Unique orders: 99,441
Duplicate orders: 0

In [77]:
customer_features = [
    "customer_unique_id",
    "customer_order_count",
    "customer_total_spend",
    "customer_avg_order_value",
    "customer_avg_review_score",
    "customer_late_order_rate",
    "customer_avg_delivery_delay",
    "customer_category_diversity",
    "customer_repeat_purchase_indicator"
]

print("=" * 70)
print("CUSTOMER FEATURE COVERAGE")
print("=" * 70)

for col in customer_features:
    if col in master_v1.columns:
        available = master_v1[col].notna().sum()
        missing = master_v1[col].isna().sum()
        print(f"{col:40} | Available: {available:6,} | Missing: {missing:6,}")
    else:
        print(f"{col:40} | ❌ COLUMN MISSING")

======================================================================
CUSTOMER FEATURE COVERAGE
======================================================================
customer_unique_id                       | Available: 99,441 | Missing:      0
customer_order_count                     | Available: 99,441 | Missing:      0
customer_total_spend                     | Available: 99,441 | Missing:      0
customer_avg_order_value                 | Available: 98,756 | Missing:    685
customer_avg_review_score                | Available: 99,441 | Missing:      0
customer_late_order_rate                 | Available: 96,681 | Missing:  2,760
customer_avg_delivery_delay              | Available: 96,681 | Missing:  2,760
customer_category_diversity              | Available: 99,441 | Missing:      0
customer_repeat_purchase_indicator       | Available: 99,441 | Missing:      0

In [78]:
print("=" * 70)
print("MISSING CUSTOMER ID CHECK")
print("=" * 70)

missing_customer_id = master_v1["customer_unique_id"].isna()

print(f"Orders with customer_unique_id:     {(~missing_customer_id).sum():,}")
print(f"Orders missing customer_unique_id:  {missing_customer_id.sum():,}")

print("\nCustomer features on orders with missing customer ID:")

customer_feature_only = [
    "customer_order_count",
    "customer_total_spend",
    "customer_avg_order_value",
    "customer_avg_review_score",
    "customer_late_order_rate",
    "customer_avg_delivery_delay",
    "customer_category_diversity",
    "customer_repeat_purchase_indicator"
]

for col in customer_feature_only:
    count = master_v1.loc[missing_customer_id, col].notna().sum()
    print(f"{col:40} | Non-missing values: {count:,}")

======================================================================
MISSING CUSTOMER ID CHECK
======================================================================
Orders with customer_unique_id:     99,441
Orders missing customer_unique_id:  0

Customer features on orders with missing customer ID:
customer_order_count                     | Non-missing values: 0
customer_total_spend                     | Non-missing values: 0
customer_avg_order_value                 | Non-missing values: 0
customer_avg_review_score                | Non-missing values: 0
customer_late_order_rate                 | Non-missing values: 0
customer_avg_delivery_delay              | Non-missing values: 0
customer_category_diversity              | Non-missing values: 0
customer_repeat_purchase_indicator       | Non-missing values: 0

In [79]:
print("=" * 70)
print("REPEAT PURCHASE VALIDATION")
print("=" * 70)

valid_customer = master_v1["customer_unique_id"].notna()

expected_repeat = (
    master_v1.loc[valid_customer, "customer_order_count"] > 1
).astype("Int64")

actual_repeat = master_v1.loc[
    valid_customer, "customer_repeat_purchase_indicator"
]

repeat_mismatch = (
    expected_repeat != actual_repeat
).sum()

print(f"Valid customer orders: {valid_customer.sum():,}")
print(f"Repeat indicator mismatches: {repeat_mismatch:,}")

if repeat_mismatch == 0:
    print("✓ PASS — Repeat purchase indicator is consistent.")
else:
    print("⚠ REVIEW — Repeat purchase indicator has inconsistencies.")

======================================================================
REPEAT PURCHASE VALIDATION
======================================================================
Valid customer orders: 99,441
Repeat indicator mismatches: 0
✓ PASS — Repeat purchase indicator is consistent.

In [80]:
print("=" * 70)
print("CUSTOMER ORDER COUNT CONSISTENCY")
print("=" * 70)

customer_count_check = (
    master_v1[valid_customer]
    .groupby("customer_unique_id")["customer_order_count"]
    .nunique()
)

inconsistent_customers = (customer_count_check > 1).sum()

print(f"Customers checked: {len(customer_count_check):,}")
print(f"Customers with inconsistent order counts: {inconsistent_customers:,}")

if inconsistent_customers == 0:
    print("✓ PASS — Customer order counts are consistent.")
else:
    print("⚠ REVIEW — Some customers have inconsistent order counts.")

======================================================================
CUSTOMER ORDER COUNT CONSISTENCY
======================================================================
Customers checked: 96,096
Customers with inconsistent order counts: 0
✓ PASS — Customer order counts are consistent.

In [81]:
print("=" * 70)
print("CUSTOMER TOTAL SPEND CONSISTENCY")
print("=" * 70)

spend_check = (
    master_v1[valid_customer]
    .groupby("customer_unique_id")["customer_total_spend"]
    .nunique()
)

inconsistent_spend = (spend_check > 1).sum()

print(f"Customers checked: {len(spend_check):,}")
print(f"Customers with inconsistent total spend: {inconsistent_spend:,}")

if inconsistent_spend == 0:
    print("✓ PASS — Customer total spend is consistent.")
else:
    print("⚠ REVIEW — Some customers have inconsistent total spend.")

======================================================================
CUSTOMER TOTAL SPEND CONSISTENCY
======================================================================
Customers checked: 96,096
Customers with inconsistent total spend: 0
✓ PASS — Customer total spend is consistent.

In [82]:
print("=" * 70)
print("CUSTOMER AVERAGE ORDER VALUE CONSISTENCY")
print("=" * 70)

avg_order_check = (
    master_v1[valid_customer]
    .groupby("customer_unique_id")["customer_avg_order_value"]
    .nunique()
)

inconsistent_avg_order = (avg_order_check > 1).sum()

print(f"Customers checked: {len(avg_order_check):,}")
print(
    f"Customers with inconsistent average order value: "
    f"{inconsistent_avg_order:,}"
)

if inconsistent_avg_order == 0:
    print("✓ PASS — Customer average order value is consistent.")
else:
    print("⚠ REVIEW — Some customers have inconsistent average order value.")

======================================================================
CUSTOMER AVERAGE ORDER VALUE CONSISTENCY
======================================================================
Customers checked: 96,096
Customers with inconsistent average order value: 0
✓ PASS — Customer average order value is consistent.

In [83]:
print("=" * 70)
print("CUSTOMER REVIEW SCORE CONSISTENCY")
print("=" * 70)

review_check = (
    master_v1[valid_customer]
    .groupby("customer_unique_id")["customer_avg_review_score"]
    .nunique()
)

inconsistent_review = (review_check > 1).sum()

print(f"Customers checked: {len(review_check):,}")
print(
    f"Customers with inconsistent average review score: "
    f"{inconsistent_review:,}"
)

if inconsistent_review == 0:
    print("✓ PASS — Customer review scores are consistent.")
else:
    print("⚠ REVIEW — Some customers have inconsistent review scores.")

======================================================================
CUSTOMER REVIEW SCORE CONSISTENCY
======================================================================
Customers checked: 96,096
Customers with inconsistent average review score: 0
✓ PASS — Customer review scores are consistent.

In [84]:
print("=" * 70)
print("CUSTOMER DELIVERY FEATURE CONSISTENCY")
print("=" * 70)

late_check = (
    master_v1[valid_customer]
    .groupby("customer_unique_id")["customer_late_order_rate"]
    .nunique()
)

delay_check = (
    master_v1[valid_customer]
    .groupby("customer_unique_id")["customer_avg_delivery_delay"]
    .nunique()
)

inconsistent_late = (late_check > 1).sum()
inconsistent_delay = (delay_check > 1).sum()

print(
    f"Customers with inconsistent late-order rate: "
    f"{inconsistent_late:,}"
)

print(
    f"Customers with inconsistent average delivery delay: "
    f"{inconsistent_delay:,}"
)

if inconsistent_late == 0:
    print("✓ Late-order rate: PASS")
else:
    print("⚠ Late-order rate: REVIEW")

if inconsistent_delay == 0:
    print("✓ Average delivery delay: PASS")
else:
    print("⚠ Average delivery delay: REVIEW")

======================================================================
CUSTOMER DELIVERY FEATURE CONSISTENCY
======================================================================
Customers with inconsistent late-order rate: 0
Customers with inconsistent average delivery delay: 0
✓ Late-order rate: PASS
✓ Average delivery delay: PASS

In [85]:
print("=" * 70)
print("CUSTOMER CATEGORY DIVERSITY CONSISTENCY")
print("=" * 70)

category_check = (
    master_v1[valid_customer]
    .groupby("customer_unique_id")["customer_category_diversity"]
    .nunique()
)

inconsistent_category = (category_check > 1).sum()

print(f"Customers checked: {len(category_check):,}")
print(
    f"Customers with inconsistent category diversity: "
    f"{inconsistent_category:,}"
)

if inconsistent_category == 0:
    print("✓ PASS — Customer category diversity is consistent.")
else:
    print("⚠ REVIEW — Some customers have inconsistent category diversity.")

======================================================================
CUSTOMER CATEGORY DIVERSITY CONSISTENCY
======================================================================
Customers checked: 96,096
Customers with inconsistent category diversity: 0
✓ PASS — Customer category diversity is consistent.

In [86]:
print("=" * 70)
print("CUSTOMER FEATURE LOGICAL VALIDATION")
print("=" * 70)

valid = master_v1["customer_unique_id"].notna()

checks = {}

checks["order_count_less_than_1"] = (
    master_v1.loc[valid, "customer_order_count"] < 1
).sum()

checks["negative_total_spend"] = (
    master_v1.loc[valid, "customer_total_spend"] < 0
).sum()

checks["negative_avg_order_value"] = (
    master_v1.loc[valid, "customer_avg_order_value"] < 0
).sum()

checks["review_score_below_1"] = (
    master_v1.loc[valid, "customer_avg_review_score"] < 1
).sum()

checks["review_score_above_5"] = (
    master_v1.loc[valid, "customer_avg_review_score"] > 5
).sum()

checks["late_rate_below_0"] = (
    master_v1.loc[valid, "customer_late_order_rate"] < 0
).sum()

checks["late_rate_above_1"] = (
    master_v1.loc[valid, "customer_late_order_rate"] > 1
).sum()

checks["category_diversity_below_0"] = (
    master_v1.loc[valid, "customer_category_diversity"] < 0
).sum()

for name, count in checks.items():
    print(f"{name:40} | {count:,}")

total_issues = sum(checks.values())

print("\n" + "-" * 70)

if total_issues == 0:
    print("✓ PASS — No logical customer-feature violations found.")
else:
    print(f"⚠ REVIEW — {total_issues:,} logical issues found.")

======================================================================
CUSTOMER FEATURE LOGICAL VALIDATION
======================================================================
order_count_less_than_1                  | 0
negative_total_spend                     | 0
negative_avg_order_value                 | 0
review_score_below_1                     | 0
review_score_above_5                     | 0
late_rate_below_0                        | 0
late_rate_above_1                        | 0
category_diversity_below_0               | 0

----------------------------------------------------------------------
✓ PASS — No logical customer-feature violations found.

In [87]:
print("=" * 70)
print("CUSTOMER ENRICHMENT VALIDATION RESULT")
print("=" * 70)

total_customer_issues = (
    repeat_mismatch
    + inconsistent_customers
    + inconsistent_spend
    + inconsistent_avg_order
    + inconsistent_review
    + inconsistent_late
    + inconsistent_delay
    + inconsistent_category
    + total_issues
)

print(f"Total customer enrichment issues: {total_customer_issues:,}")

print()

if total_customer_issues == 0:
    print("✓ PASS — Customer enrichment is internally consistent.")
else:
    print("⚠ REVIEW — Customer enrichment requires investigation.")

print("=" * 70)

======================================================================
CUSTOMER ENRICHMENT VALIDATION RESULT
======================================================================
Total customer enrichment issues: 0

✓ PASS — Customer enrichment is internally consistent.
======================================================================

In [88]:
print("=" * 70)
print("PHASE 1 — FINAL MASTER DATASET VALIDATION")
print("=" * 70)

print(f"Rows: {len(master_v1):,}")
print(f"Columns: {len(master_v1.columns):,}")
print(f"Unique order IDs: {master_v1['order_id'].nunique():,}")
print(f"Duplicate order IDs: {master_v1['order_id'].duplicated().sum():,}")

print("\n" + "-" * 70)
print("EXPECTED STRUCTURE")
print("-" * 70)

if (
    len(master_v1) == master_v1["order_id"].nunique()
    and master_v1["order_id"].duplicated().sum() == 0
):
    print("✓ PASS — One row per order.")
else:
    print("⚠ FAIL — Order-level uniqueness problem.")

print("\n" + "-" * 70)
print("CUSTOMER ID COVERAGE")
print("-" * 70)

print(
    f"Orders with customer_unique_id: "
    f"{master_v1['customer_unique_id'].notna().sum():,}"
)

print(
    f"Orders without customer_unique_id: "
    f"{master_v1['customer_unique_id'].isna().sum():,}"
)

print("\n" + "-" * 70)
print("CUSTOMER FEATURES ON UNKNOWN CUSTOMERS")
print("-" * 70)

unknown_customer = master_v1["customer_unique_id"].isna()

customer_feature_leakage = 0

for col in customer_feature_only:
    count = master_v1.loc[unknown_customer, col].notna().sum()
    customer_feature_leakage += count
    print(f"{col:40} | Non-missing: {count:,}")

if customer_feature_leakage == 0:
    print("\n✓ PASS — No customer-level features assigned to unknown customers.")
else:
    print(
        f"\n⚠ REVIEW — {customer_feature_leakage:,} "
        "customer-feature values exist for unknown customers."
    )

======================================================================
PHASE 1 — FINAL MASTER DATASET VALIDATION
======================================================================
Rows: 99,441
Columns: 51
Unique order IDs: 99,441
Duplicate order IDs: 0

----------------------------------------------------------------------
EXPECTED STRUCTURE
----------------------------------------------------------------------
✓ PASS — One row per order.

----------------------------------------------------------------------
CUSTOMER ID COVERAGE
----------------------------------------------------------------------
Orders with customer_unique_id: 99,441
Orders without customer_unique_id: 0

----------------------------------------------------------------------
CUSTOMER FEATURES ON UNKNOWN CUSTOMERS
----------------------------------------------------------------------
customer_order_count                     | Non-missing: 0
customer_total_spend                     | Non-missing: 0
customer_avg_order_value                 | Non-missing: 0
customer_avg_review_score                | Non-missing: 0
customer_late_order_rate                 | Non-missing: 0
customer_avg_delivery_delay              | Non-missing: 0
customer_category_diversity              | Non-missing: 0
customer_repeat_purchase_indicator       | Non-missing: 0

✓ PASS — No customer-level features assigned to unknown customers.

In [89]:
OUTPUT_FILE = "master_v1_phase1_validated.csv"

master_v1.to_csv(
    OUTPUT_FILE,
    index=False
)

print("=" * 70)
print("PHASE 1 — VALIDATED DATASET SAVED")
print("=" * 70)

print(f"File: {OUTPUT_FILE}")
print(f"Rows: {len(master_v1):,}")
print(f"Columns: {len(master_v1.columns):,}")
print(f"Unique orders: {master_v1['order_id'].nunique():,}")
print(f"Duplicate orders: {master_v1['order_id'].duplicated().sum():,}")

======================================================================
PHASE 1 — VALIDATED DATASET SAVED
======================================================================
File: master_v1_phase1_validated.csv
Rows: 99,441
Columns: 51
Unique orders: 99,441
Duplicate orders: 0